### ISSUE TITLE
Font sizes too big

### ISSUE THREAD

**Issue by ScottHutchinson** [fwaris/BertQA#1]
Thanks for making this demo app available. It's very cool. I used it to introduce my team to Fabulous.

It all worked perfectly, except that the font sizes were all way too big. When I first tried to use it in the Android emulator on Windows, I could not see the questions, because the content font was so big it was taking up the whole screen.

I got it to work by adding code like `fontSize = FontSize.FontSize(8.0),` to all the Labels.

Not sure what the real fix should be. I'm a complete novice at mobile development.

**Comment by fwaris** [comment]
@ScottHutchinson  good to know that the app is useful. 

I believe the correct way to style the app is via the CSS type capability of Xamarin forms. I plan to do that next. Its something that I am still learning.
